name: Build Windows Installer

on:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build renderer assets
        run: npm run build:webpack

      - name: Package Windows app
        run: npx electron-builder --win

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist/
